#!/usr/bin/sh
sxhkd &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
xrandr --output LVDS --off --output HDMI-0 --primary --mode 1600x900 --pos 0x0 --rotate normal --output VGA-0 --off

bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# AutoStart
feh --bg-fill /mnt/Datos/Wallpapers/wallpaperflare.com_wallpaper.rotated.jpg
# nm-applet &
picom --no-vsync &
$HOME/.config/polybar/launch.sh
